# Generated by Django 5.1.2 on 2025-01-09 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0003_rename_transportadora_clientes_seguradora'),
        ('produto', '0001_initial'),
        ('requisicao', '0039_alter_requisicoes_faturamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='antenista_CARD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Atualizado', 'Atualizado'), ('Reprovado', 'Reprovado'), ('Pendente', 'Pendente')], default='Pendente', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenista_card2', to='acompanhamento.clientes')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenista_teste', to='requisicao.estoque_antenista')),
                ('tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenista_card_produto', to='produto.produto')),
            ],
        ),
    ]
