# Generated by Django 5.1.2 on 2025-01-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0040_antenista_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenista_card',
            name='cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
