# Generated by Django 5.1.2 on 2025-01-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0041_alter_antenista_card_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antenista_card',
            old_name='nome',
            new_name='antenista',
        ),
        migrations.AddField(
            model_name='antenista_card',
            name='nome_do_solicitante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
