# Generated by Django 5.1.2 on 2025-02-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0045_alter_antenista_card_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Tipo de Faturamento', 'Tipo de Faturamento'), ('Aquisicão Nova', 'Aquisicão Nova'), ('Manutenção', 'Manutenção'), ('Aditivo', 'Aditivo'), ('Acessórios', 'Acessórios'), ('Extravio', 'Extravio'), ('Teste', 'Teste'), ('Spot', 'Spot'), ('Isca Fast - Agente', 'Isca Fast - Agente'), ('Antenista', 'Antenista'), ('Reversa', 'Reversa'), ('Isca FAST', 'Isca FAST'), ('Estoque Antenista', 'Estoque Antenista'), ('Renovação', 'Renovação')], default='', max_length=50, null=True),
        ),
    ]
