# Generated by Django 5.1.2 on 2025-04-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0047_alter_antenista_card_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenista_card',
            name='valor_entrega',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
