# Generated by Django 5.1.2 on 2025-04-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0048_antenista_card_valor_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenista_card',
            name='valor_entrega',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
