# Generated by Django 5.1.2 on 2025-04-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0049_alter_antenista_card_valor_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='comercial',
            field=models.CharField(blank=True, choices=[('MAYRA', 'MAYRA'), ('DANIEL', 'DANIEL'), ('MARCIO', 'MARCIO'), ('CIDO', 'CIDO'), ('ALISON', 'ALISON'), ('THIAGO', 'THIAGO'), ('GOLDEN', 'GOLDEN'), ('ARMANDO', 'ARMANDO')], default='', max_length=100),
        ),
    ]
