# Generated by Django 5.1.2 on 2025-04-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0050_alter_requisicoes_comercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='comercial',
            field=models.CharField(blank=True, choices=[('MAYRA', 'MAYRA'), ('DANIEL', 'DANIEL'), ('MARCIO', 'MARCIO'), ('CIDO', 'CIDO'), ('ALISON', 'ALISON'), ('THIAGO', 'THIAGO'), ('GOLDEN', 'GOLDEN'), ('ARMANDO', 'ARMANDO'), ('INFINITY', 'INFINITY')], default='', max_length=100),
        ),
    ]
