# Generated by Django 5.1.2 on 2025-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0052_remove_antenista_card_valor_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenista_card',
            name='valor_entrega',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
