# Generated by Django 5.1.2 on 2025-06-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0054_alter_antenista_card_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='comercial',
            field=models.CharField(blank=True, choices=[('MAYRA', 'MAYRA'), ('DANIEL', 'DANIEL'), ('MARCIO', 'MARCIO'), ('CIDO', 'CIDO'), ('ALISON', 'ALISON'), ('THIAGO', 'THIAGO'), ('GOLDEN', 'GOLDEN'), ('ARMANDO', 'ARMANDO'), ('INFINITY', 'INFINITY'), ('MALUFF', 'MALUFF')], default='', max_length=100),
        ),
    ]
