# Generated by Django 5.2.3 on 2025-09-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0056_antenista_card_data_criacao_estoque_antenista_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='iccid',
            field=models.CharField(blank=True, default='', max_length=600000, null=True),
        ),
    ]
