# Generated by Django 5.1.2 on 2025-01-03 12:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipamento', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=100)),
                ('data_insercao', models.DateTimeField(default=django.utils.timezone.now)),
                ('operacao', models.CharField(choices=[('Santa Cruz', 'Santa Cruz'), ('Prysmian', 'Prysmian'), ('Lauto', 'Lauto'), ('Fast Shop', 'Fast Shop')], max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
