# Generated by Django 5.1.2 on 2025-01-02 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('registrodemanutencao', '0013_imagemregistro_imagem2_registrodemanutencao_imagem2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrodemanutencao',
            name='faturamento',
        ),
        migrations.RemoveField(
            model_name='registrodemanutencao',
            name='setor',
        ),
        migrations.AddField(
            model_name='imagemregistro',
            name='faturamento',
            field=models.CharField(blank=True, choices=[('', ''), ('Com_Custo', 'Com Custo'), ('Sem_Custo', 'Sem Custo')], default='Pendente', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagemregistro',
            name='observacao2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registrodemanutencao',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodemanutencao',
            name='customizacaoo',
            field=models.CharField(blank=True, choices=[('Sem custumização', 'Sem custumização'), ('Caixa de papelão', 'Caixa de papelão'), ('Caixa de papelão (bateria desacoplada)', 'Caixa de papelão (bateria desacoplada)'), ('Caixa de papelão + DF', 'Caixa de papelão + DF'), ('Termo branco', 'Termo branco'), ('Termo branco + Imã', 'Termo branco + Imã'), ('Termo branco + D.F', 'Termo branco + D.F'), ('Termo branco slim', 'Termo branco slim'), ('Termo branco slim + D.F +EQT', 'Termo branco slim + D.F +EQT'), ('Termo cinza slim + D.F +EQT', 'Termo cinza slim + D.F +EQT'), ('Termo branco (isopor)', 'Termo branco (isopor)'), ('Termo branco - bateria externa', 'Termo branco - bateria externa'), ('Termo marrom + imã', 'Termo marrom + imã'), ('Termo cinza', 'Termo cinza'), ('Termo cinza + imã', 'Termo cinza + imã'), ('Termo preto', 'Termo preto'), ('Termo preto + imã', 'Termo preto + imã'), ('Termo brabco |marrim-slim', 'Termo brabco |marrim-slim'), ('Termo marrom slim +D.F + EQT', 'Termo marrom slim +D.F + EQT'), ('Termo marrom', 'Termo marrom'), ('Caixa blindada', 'Caixa blindada'), ('Tênis/ Sapato', 'Tênis/ Sapato'), ('Projetor', 'Projetor'), ('Caixa de som', 'Caixa de som'), ('Luminaria', 'Luminaria'), ('Alexa', 'Alexa'), ('Video Game', 'Video Game'), ('Secador de cabelo', 'Secador de cabelo'), ('Roteador', 'Roteador'), ('Relogio digital', 'Relogio digital')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='registrodemanutencao',
            name='entregue_por_retirado_por',
            field=models.CharField(blank=True, choices=[('Correios/Transportadora', 'Correios/Transportadora'), ('Entrega na base', 'Entrega na base'), ('Motoboy', 'Motoboy')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrodemanutencao',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registrodemanutencao',
            name='tipo_produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulario_produto', to='produto.produto'),
        ),
    ]
