# Generated by Django 5.1.2 on 2025-01-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0015_alter_imagemregistro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemregistro',
            name='faturamento',
            field=models.CharField(blank=True, choices=[('', ''), ('Com_Custo', 'Com Custo'), ('Sem_Custo', 'Sem Custo')], default='', max_length=50, null=True),
        ),
    ]
