# Generated by Django 5.1.2 on 2025-01-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0016_alter_imagemregistro_faturamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemregistro',
            name='imagem',
            field=models.ImageField(upload_to='imagens_registros/'),
        ),
        migrations.AlterField(
            model_name='imagemregistro',
            name='tipo_problema',
            field=models.CharField(blank=True, choices=[('Oxidação', 'Oxidação'), ('Placa Danificada', 'Placa Danificada'), ('Placa danificada SEM CUSTO', 'Placa danificada SEM CUSTO'), ('USB Danificado', 'USB Danificado'), ('USB Danificado SEM CUSTO', 'USB Danificado SEM CUSTO'), ('Botão de acionamento Danificado', 'Botão de acionamento Danificado'), ('Botão de acionamento Danificado SEM CUSTO', 'Botão de acionamento Danificado SEM CUSTO'), ('Antena LoRa Danificada', 'Antena LoRa Danificada'), ('Sem problemas Identificados', 'Sem problemas Identificados'), ('Antena 4G danificada ', 'Antena 4G danificada ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrodemanutencao',
            name='tratativa',
            field=models.CharField(blank=True, choices=[('Oxidação', 'Oxidação'), ('Placa Danificada', 'Placa Danificada'), ('USB Danificado', 'USB Danificado'), ('Botão de acionamento Danificado', 'Botão de acionamento Danificado'), ('Antena LoRa Danificada', 'Antena LoRa Danificada'), ('USB Sem problemas Identificados', 'USB Sem problemas Identificados'), ('Antena 4G danificada ', 'Antena 4G danificada ')], max_length=50, null=True),
        ),
    ]
