# Generated by Django 5.1.2 on 2025-01-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0017_alter_imagemregistro_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemregistro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
    ]
