# Generated by Django 5.1.2 on 2025-08-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0021_alter_imagemregistro_tipo_problema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodemanutencao',
            name='status_tratativa',
            field=models.CharField(blank=True, choices=[('Pendente de Tratativa', 'Pendente de Tratativa'), ('Tratada', 'Tratada'), ('Faturada', 'Faturada')], default='Pendente de Tratativa', max_length=50, null=True),
        ),
    ]
