# Generated by Django 5.2.3 on 2025-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0022_registrodemanutencao_status_tratativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodemanutencao',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('Descartavel', 'Descartavel'), ('Retornavel', 'Retornavel')], max_length=50, null=True),
        ),
    ]
