# Generated by Django 5.1.2 on 2025-05-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('data_entrada', models.CharField(blank=True, max_length=50, null=True)),
                ('pesquisa', models.CharField(blank=True, max_length=50, null=True)),
                ('estado1', models.CharField(blank=True, max_length=50, null=True)),
                ('estado2', models.CharField(blank=True, max_length=50, null=True)),
                ('estado3', models.CharField(blank=True, max_length=50, null=True)),
                ('estado4', models.CharField(blank=True, max_length=50, null=True)),
                ('estado5', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_devolutiva', models.CharField(blank=True, max_length=50, null=True)),
                ('sla', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo', models.CharField(blank=True, max_length=50, null=True)),
                ('estados', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.CharField(blank=True, max_length=50, null=True)),
                ('modo', models.CharField(blank=True, choices=[('Pesquisa', 'Pesquisa'), ('consulta', 'Consulta')], max_length=50, null=True)),
                ('plano', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Combo', 'Combo')], max_length=50, null=True)),
                ('perfil', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(blank=True, max_length=50, null=True)),
                ('resultado', models.CharField(blank=True, choices=[('Adequado', 'Adequado'), ('Inadequado', 'Inadequado')], max_length=50, null=True)),
                ('periodo', models.CharField(blank=True, choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], max_length=50, null=True)),
            ],
        ),
    ]
