# Generated by Django 5.1.2 on 2025-05-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='cpfcnpj',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
