# Generated by Django 5.1.2 on 2025-02-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0003_rename_transportadora_clientes_seguradora'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='quantidade_em_contrato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
