# Generated by Django 5.1.2 on 2025-04-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0004_clientes_quantidade_em_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='data_treinamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
