# Generated by Django 5.1.2 on 2025-05-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0005_clientes_data_treinamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='data_treinamento',
        ),
        migrations.AddField(
            model_name='clientes',
            name='comercial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
