# Generated by Django 5.1.2 on 2025-06-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0006_remove_clientes_data_treinamento_clientes_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='data_treinamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
