# Generated by Django 5.1.2 on 2025-05-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0002_remove_gridinternacional_ultimo_grid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridinternacional',
            name='requisicao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Requisição'),
        ),
        migrations.AddField(
            model_name='gridinternacional',
            name='ultimo_grid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Último Grid'),
        ),
    ]
