# Generated by Django 5.1.2 on 2025-05-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0005_remove_gridinternacional_ultimo_grid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientesNestle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente')),
                ('cnpj', models.CharField(blank=True, max_length=255, null=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('quantidade', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='Quantidade')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local')),
            ],
        ),
    ]
