# Generated by Django 5.1.2 on 2025-05-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0006_clientesnestle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientesnestle',
            name='local',
        ),
    ]
