# Generated by Django 5.1.2 on 2025-05-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0011_gridinternacional_data_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gridinternacional',
            name='data_invoice',
        ),
        migrations.AlterField(
            model_name='gridinternacional',
            name='data_envoice',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RF Invoice'),
        ),
    ]
