# Generated by Django 5.1.2 on 2025-05-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0012_remove_gridinternacional_data_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridinternacional',
            name='sla_destino',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SLA Destino'),
        ),
    ]
