# Generated by Django 5.1.2 on 2025-05-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0015_alter_gridinternacional_status_operacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridinternacional',
            name='sla_liberacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
