# Generated by Django 5.1.2 on 2024-11-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPagamento',
            fields=[
                ('cliente', models.CharField(choices=[('Sompo', 'Sompo')], max_length=50, null=True)),
                ('data_hora_inicial', models.DateTimeField()),
                ('data_hora_final', models.DateTimeField()),
                ('prestador', models.CharField(max_length=100)),
                ('rastreador', models.CharField(max_length=100, null=True)),
                ('isca', models.CharField(blank=True, max_length=100)),
                ('acionamento', models.CharField(max_length=100)),
                ('hora_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('franquia_hora', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_hora_excedente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('placas', models.CharField(max_length=100)),
                ('agentes', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_excedente', models.DecimalField(decimal_places=2, max_digits=5)),
                ('km_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_excedente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_franquia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_km_excedente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total_km_excedente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedagio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(default='Pendente', max_length=50, null=True)),
            ],
        ),
    ]
