# Generated by Django 5.1.2 on 2024-11-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0002_registropagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registropagamento',
            old_name='descricao',
            new_name='descricao_de_acionamento',
        ),
    ]
