# Generated by Django 5.1.2 on 2024-11-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0003_rename_descricao_registropagamento_descricao_de_acionamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('hora_excedente', models.FloatField()),
                ('valor_hora_excedente', models.FloatField()),
                ('km_excedente', models.FloatField()),
                ('valor_km_excedente', models.FloatField()),
                ('acionamento', models.FloatField()),
                ('total_cliente', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='registropagamento',
            old_name='descricao_de_acionamento',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='modelo_cor_ano',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='operador',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='protocolo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='quantidade_agentes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='solicitante',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='tipo_contato',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='ultima_posicao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
