# Generated by Django 5.1.2 on 2024-12-16 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0004_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes_acionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('franquiakm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('franquiahora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valordeacionamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='prestadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=50, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=50, null=True)),
                ('vencimento_cnh', models.DateField()),
                ('tipo_prestador', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('dados_bancarios', models.CharField(blank=True, max_length=50, null=True)),
                ('disponibilidade', models.CharField(blank=True, max_length=50, null=True)),
                ('regiao_atuacao', models.CharField(blank=True, max_length=50, null=True)),
                ('status_prestador', models.CharField(blank=True, max_length=50, null=True)),
                ('franquia_hora', models.IntegerField()),
                ('valorkm', models.IntegerField(blank=True, null=True)),
                ('valorh', models.IntegerField(blank=True, null=True)),
                ('franquia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_acionamento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cnh', models.ImageField(blank=True, null=True, upload_to='imagens_registros/')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagens_registros/')),
            ],
        ),
        migrations.RemoveField(
            model_name='registro',
            name='hora_excedente',
        ),
        migrations.RemoveField(
            model_name='registropagamento',
            name='modelo_cor_ano',
        ),
        migrations.AddField(
            model_name='registro',
            name='valor_acionamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='ano',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='cor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='data_hora_chegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='id_equipamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='id_isca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem10',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem11',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem12',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem13',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem14',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem15',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem16',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem4',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem5',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem6',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem7',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem8',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='imagem9',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_registros/'),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='latlong',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='latlong_isca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='previsa_chegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='sla',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='total_acionamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registropagamento',
            name='ultima_posicao_isca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='acionamento',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='km_excedente',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='total_cliente',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='registro',
            name='valor_hora_excedente',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='valor_km_excedente',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='acionamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='agentes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='cliente',
            field=models.CharField(blank=True, choices=[('Sompo', 'Sompo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='data_hora_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='data_hora_inicial',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='franquia_hora',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='hora_excedente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='hora_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='isca',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='km_excedente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='km_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='km_franquia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='km_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='km_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='operador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='pedagio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='placas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='protocolo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='quantidade_agentes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='rastreador',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='solicitante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='status',
            field=models.CharField(blank=True, default='Pendente', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Pronta Resposta Armado', 'Pronta Resposta Armado'), ('Pronta Resposta Desarmado', 'Pronta Resposta Desarmado'), ('Antenista', 'Antenista'), ('Antenista e Pronta Resposta Armado', 'Antenista e Pronta Resposta Armado'), ('Antenista e Pronta Resposta Desarmado', 'Antenista e Pronta Resposta Desarmado'), ('Pronta Resposta Armado e Pronta Resposta Desarmado', 'Antenista e Pronta Resposta Desarmado')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='tipo_contato',
            field=models.CharField(blank=True, choices=[('Whatsapp', 'Whatsapp'), ('E-mail', 'E-mail'), ('Telefone', 'Telefone')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='ultima_posicao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='valor_hora_excedente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='valor_km_excedente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='valor_total_km_excedente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='prestador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestadores', to='formacompanhamento.prestadores'),
        ),
        migrations.CreateModel(
            name='TotalRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_acionamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('km_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hora_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('franquia_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('franquia_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_acionamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacompanhamento.clientes_acionamento')),
                ('registro_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacompanhamento.registropagamento')),
            ],
        ),
    ]
