# Generated by Django 5.1.2 on 2025-01-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0005_clientes_acionamento_prestadores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestadores',
            name='status_prestador',
            field=models.CharField(blank=True, choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('PENDENTE', 'PENDENTE')], max_length=50, null=True),
        ),
    ]
