# Generated by Django 5.1.2 on 2025-01-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0006_alter_prestadores_status_prestador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropagamento',
            name='km_franquia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
