# Generated by Django 5.1.2 on 2025-01-31 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0007_alter_registropagamento_km_franquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropagamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formacompanhamento.clientes_acionamento'),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='registropagamento',
            name='prestador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestadores', to='formacompanhamento.prestadores'),
        ),
    ]
