# Generated by Django 5.1.2 on 2025-02-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0008_alter_registropagamento_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestadores',
            name='franquia_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='prestadores',
            name='franquia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='prestadores',
            name='status_prestador',
            field=models.CharField(blank=True, choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('PENDENTE', 'PENDENTE')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prestadores',
            name='valor_acionamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='prestadores',
            name='valorh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='prestadores',
            name='valorkm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='prestadores',
            name='vencimento_cnh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
