# Generated by Django 5.1.2 on 2025-02-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0009_alter_prestadores_franquia_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestadores',
            name='franquia_hora',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestadores',
            name='franquia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='prestadores',
            name='status_prestador',
            field=models.CharField(blank=True, choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('PENDENTE', 'PENDENTE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prestadores',
            name='valor_acionamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='prestadores',
            name='valorh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestadores',
            name='valorkm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
