# Generated by Django 5.1.2 on 2025-02-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0010_alter_prestadores_franquia_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestadores',
            name='franquia_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='prestadores',
            name='valorh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='prestadores',
            name='valorkm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
