# Generated by Django 5.1.2 on 2025-02-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacompanhamento', '0011_alter_prestadores_franquia_hora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestadores',
            old_name='dados_bancarios',
            new_name='agencia',
        ),
        migrations.AddField(
            model_name='prestadores',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prestadores',
            name='conta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prestadores',
            name='tipo_de_conta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
