# Generated by Django 5.1.2 on 2025-05-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridInternacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente')),
                ('local_de_entrega', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local de Entrega')),
                ('modelo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modelo')),
                ('id_planilha', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID')),
                ('ccid', models.CharField(blank=True, max_length=255, null=True, verbose_name='CCID')),
                ('sla_insercao', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLA de Inserção')),
                ('data_insercao', models.DateField(blank=True, null=True, verbose_name='Data / Inserção')),
                ('destino', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destino')),
                ('bl', models.CharField(blank=True, max_length=255, null=True, verbose_name='BL')),
                ('container', models.CharField(blank=True, max_length=255, null=True, verbose_name='Container')),
                ('sla_viagem', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLA de Viagem')),
                ('data_chegada_destino', models.DateField(blank=True, null=True, verbose_name='Data / Chegada no Destino')),
                ('sla_retirada', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLA de Retirada')),
                ('data_retirada', models.DateField(blank=True, null=True, verbose_name='Data / Retirada')),
                ('sla_envio_brasil', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLA / Envio ao Brasil')),
                ('data_envio_brasil', models.DateField(blank=True, null=True, verbose_name='Data / Envio ao Brasil')),
                ('sla_chegada_brasil', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLA / Chegada ao Brasil')),
                ('data_brasil', models.DateField(blank=True, null=True, verbose_name='Data / Brasil')),
                ('status_operacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status / Operação')),
                ('sla_operacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLA da Operação')),
                ('reposicao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reposição')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_chegada_porto', models.DateField(blank=True, null=True, verbose_name='Data / Chegada no Porto')),
                ('data_embarque_maritimo', models.DateField(blank=True, null=True, verbose_name='Data / Embarque Marítimo')),
                ('data_desembarque_maritimo', models.DateField(blank=True, null=True, verbose_name='Data / Desembarque Marítimo')),
                ('data_chegada_terminal', models.DateField(blank=True, null=True, verbose_name='Data / Chegada no Terminal')),
                ('data_saida_terminal', models.DateField(blank=True, null=True, verbose_name='Data / Saída do Terminal')),
                ('sla_porto_nacional', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLA Porto Nacional')),
                ('sla_terrestre', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLA Terrestre')),
                ('sla_maritimo', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLA Marítimo')),
                ('sla_terminal_internacional', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLA Terminal Internacional')),
                ('sla_terrestre_internacional', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLA Terrestre Internacional')),
                ('local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local')),
                ('status_container', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status do Container')),
                ('data_desembarque', models.DateField(blank=True, null=True, verbose_name='Data do Desembarque')),
                ('sla_internacional', models.CharField(blank=True, max_length=255, null=True, verbose_name='SLA Internacional')),
                ('ultimo_grid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Último Grid')),
            ],
        ),
    ]
