# Generated by Django 5.1.2 on 2025-05-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gridinternacional',
            name='ultimo_grid',
        ),
        migrations.AddField(
            model_name='gridinternacional',
            name='data_envio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Envio'),
        ),
    ]
