# Generated by Django 5.1.2 on 2025-05-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0003_gridinternacional_requisicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridinternacional',
            name='data_envoice',
            field=models.DateField(blank=True, null=True, verbose_name='Data / envoice'),
        ),
    ]
