# Generated by Django 5.1.2 on 2025-05-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0004_gridinternacional_data_envoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gridinternacional',
            name='ultimo_grid',
        ),
        migrations.AddField(
            model_name='gridinternacional',
            name='coleta',
            field=models.DateField(blank=True, null=True, verbose_name='Coleta'),
        ),
        migrations.AddField(
            model_name='gridinternacional',
            name='golden_sat',
            field=models.DateField(blank=True, null=True, verbose_name='GoldenSat'),
        ),
        migrations.AddField(
            model_name='gridinternacional',
            name='liberacao',
            field=models.DateField(blank=True, null=True, verbose_name='Liberacao'),
        ),
        migrations.AddField(
            model_name='gridinternacional',
            name='rf_invoice',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RF Invoice'),
        ),
    ]
