# Generated by Django 5.1.2 on 2025-05-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0007_remove_clientesnestle_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesnestle',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local'),
        ),
    ]
