# Generated by Django 5.1.2 on 2025-05-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0008_clientesnestle_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesnestle',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
    ]
