# Generated by Django 5.1.2 on 2025-05-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0013_gridinternacional_sla_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridinternacional',
            name='data_envoice',
            field=models.DateField(blank=True, null=True, verbose_name='Data / envoice'),
        ),
    ]
