# Generated by Django 5.1.2 on 2025-04-17 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='horas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_choice', models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado')], max_length=50, null=True)),
                ('comprovante1', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('hora_inicial', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_final', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('comprovante2', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('motivo', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('total_de_horas', models.CharField(blank=True, max_length=50, null=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
