# Generated by Django 5.2.3 on 2025-08-27 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturamento', models.DateField(blank=True, null=True)),
                ('emissao', models.DateField(blank=True, null=True)),
                ('reajustado', models.CharField(blank=True, choices=[('Reajustado', 'Reajustado'), ('Renovado', 'Renovado'), ('Reajuste', 'Reajuste'), ('OK', 'OK')], max_length=100, null=True)),
                ('reajuste', models.DateField(blank=True, null=True)),
                ('contrato', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=100, null=True)),
                ('tempo', models.CharField(blank=True, choices=[('4', '4'), ('6', '6'), ('12', '12'), ('24', '24'), ('36', '36'), ('48', '48'), ('60', '60'), ('72', '72')], max_length=100, null=True)),
                ('comercial', models.CharField(blank=True, choices=[('Marcio', 'Marcio'), ('Cido', 'Cido'), ('Daniel', 'Daniel'), ('Fabio', 'Fabio'), ('Alison', 'Alison'), ('Marcia', 'Marcia'), ('Mayra', 'Mayra'), ('Penha', 'Penha'), ('Golden', 'Golden'), ('Rubens', 'Rubens'), ('Sheyla', 'Sheyla')], max_length=100, null=True)),
                ('n_contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('sistema_omie', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.CharField(blank=True, choices=[('Nife - ita', 'Nife - ita')], max_length=100, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('tipo_servico', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('Boleto', 'Boleto'), ('Transferência', 'Transferência')], max_length=100, null=True)),
                ('vecimento', models.DateField(blank=True, null=True)),
                ('documento', models.CharField(blank=True, choices=[('Recibo', 'Recibo'), ('NF', 'NF')], max_length=100, null=True)),
                ('valor_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coluna1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('juros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_pgto', models.DateField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status2', models.CharField(blank=True, choices=[('Recebido', 'Recebido'), ('A Receber', 'A Receber')], max_length=100, null=True)),
                ('situacao', models.CharField(blank=True, choices=[('OK', 'OK'), ('Em Dia', 'Em Dia'), ('Vence em Breve', 'Vence em Breve'), ('Vence Hoje', 'Vence Hoje'), ('Vencida', 'Vencida')], max_length=100, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
