# Generated by Django 5.2.3 on 2025-08-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0003_alter_faturamento_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faturamento',
            name='tipo_contrato',
        ),
        migrations.AddField(
            model_name='faturamento',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('Recibo', 'Recibo'), ('NF', 'NF')], max_length=100, null=True),
        ),
    ]
