# Generated by Django 5.2.3 on 2025-08-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0004_remove_faturamento_tipo_contrato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faturamento',
            old_name='vecimento',
            new_name='vecimento_documento',
        ),
        migrations.RemoveField(
            model_name='faturamento',
            name='documento',
        ),
    ]
