# Generated by Django 5.2.3 on 2025-08-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0005_rename_vecimento_faturamento_vecimento_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamento',
            name='contrato',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='reajustado',
            field=models.CharField(blank=True, choices=[('RENOVADO', 'RENOVADO'), ('REAJUSTADO', 'REAJUSTADO'), ('*REAJUSTE*', '*REAJUSTE*'), ('OK', 'OK')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='situacao',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Em dia', 'Em dia'), ('Vence em breve', 'Vence em breve'), ('Vence Hoje', 'Vence Hoje'), ('Vencida', 'Vencida')], max_length=100, null=True),
        ),
    ]
