# Generated by Django 5.1.2 on 2024-11-04 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0035_rename_nome_posto_paradasegura_tipo_posto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradasegura',
            name='foto_documento_cavalo',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_documento_cavalo/'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_posto', models.CharField(choices=[('POSTO GRAAL RUBI', 'POSTO GRAAL RUBI'), ('POSTO CAPIXABOM', 'POSTO CAPIXABOM'), ('POSTO BURITIZINHO', 'POSTO BURITIZINHO'), ('POSTO TREVÃO', 'POSTO TREVÃO'), ('POSTO DA SERRA', 'POSTO DA SERRA'), ('POSTO JN', 'POSTO JN'), ('POSTO BRASILEIRÃO', 'POSTO BRASILEIRÃO')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
