# Generated by Django 5.1.2 on 2024-10-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0035_rename_nome_posto_paradasegura_tipo_posto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradasegura',
            name='foto_documento_cavalo',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_documento_cavalo/'),
        ),
    ]
