# Generated by Django 5.1.2 on 2024-11-04 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0036_alter_paradasegura_foto_documento_cavalo_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_posto', models.CharField(choices=[('ps_graal_ruby', 'POSTO GRAAL RUBI'), ('ps_capixabom', 'POSTO CAPIXABOM'), ('ps_buritizinho', 'POSTO BURITIZINHO'), ('ps_trevao', 'POSTO TREVÃO'), ('ps_serra', 'POSTO DA SERRA'), ('ps_jn', 'POSTO JN'), ('ps_brasileirao', 'POSTO BRASILEIRÃO')], default='ps_serra', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
