# Generated by Django 5.1.2 on 2024-11-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0037_userprofile_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
