# Generated by Django 5.1.2 on 2024-11-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0036_alter_paradasegura_foto_documento_cavalo'),
        ('pparada', '0038_delete_userprofile'),
    ]

    operations = [
    ]
