# Generated by Django 5.1.2 on 2024-11-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0039_merge_20241106_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradasegura',
            name='embarcador',
            field=models.CharField(blank=True, choices=[('CORTEVA', 'CORTEVA'), ('BAYER', 'BAYER'), ('COMANDO LOG', 'COMANDO LOG')], max_length=255, null=True),
        ),
    ]
