# Generated by Django 5.1.2 on 2024-11-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0040_alter_paradasegura_embarcador'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradasegura',
            name='siente_do_projeto',
            field=models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=50, null=True),
        ),
    ]
