# Generated by Django 5.1.2 on 2025-01-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pparada', '0041_paradasegura_siente_do_projeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradasegura',
            old_name='siente_do_projeto',
            new_name='ciente_do_projeto',
        ),
    ]
