# Generated by Django 5.1.2 on 2025-05-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0009_alter_clientesnestle_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridinternacional',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
