# Generated by Django 5.1.2 on 2025-05-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0010_alter_gridinternacional_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridinternacional',
            name='data_invoice',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RF Invoice'),
        ),
    ]
