# Generated by Django 5.1.2 on 2025-05-29 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0015_alter_gridinternacional_status_operacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorMensalCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2)),
                ('ano', models.IntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('enviado', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nestle.clientesnestle')),
            ],
            options={
                'ordering': ['cliente__cliente', 'ano', 'mes'],
                'unique_together': {('cliente', 'mes', 'ano')},
            },
        ),
    ]
