# Generated by Django 5.1.2 on 2025-06-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0016_valormensalcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo_transportadora', models.CharField(choices=[('FEDEX', 'FedEx'), ('DHL', 'DHL'), ('Agente', 'Agente')], default='Agente', max_length=15, verbose_name='Transportadora')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Reprovada', 'Reprovada')], default='Pendente', max_length=10, verbose_name='Status da Cotação')),
                ('frete_all_in_valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Frete ALL IN (EUR)')),
                ('frete_all_in_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Frete ALL IN (USD)')),
                ('frete_all_in_moeda', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dólar'), ('BRL', 'Real')], max_length=3, verbose_name='Moeda')),
                ('frete_all_in_brl', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('cotacao_usada', models.DecimalField(decimal_places=4, editable=False, max_digits=10)),
                ('cotacao_dolar_na_data', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=10, null=True)),
                ('cotacao_euro_na_data', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=10, null=True)),
                ('frete_all_in_eur_brl', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('frete_all_in_usd_brl', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('honorarios', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frete_rodoviario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('licenca_importacao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa_siscomex', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa_armazenagem', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qtd_equipamento', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('valor_por_equip', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('rf_invoice', models.CharField(blank=True, max_length=255, null=True, verbose_name='RF Invoice')),
                ('data_invoice', models.DateField(blank=True, null=True, verbose_name='Data Invoice')),
                ('origem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origem')),
            ],
        ),
    ]
