# Generated by Django 5.1.2 on 2025-06-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0017_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridinternacional',
            name='ultimo_grid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
