# Generated by Django 5.1.2 on 2025-06-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0018_alter_gridinternacional_ultimo_grid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gridinternacional',
            name='ultimo_grid',
        ),
        migrations.AddField(
            model_name='carga',
            name='frete_all_in_usd_moeda',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dólar'), ('BRL', 'Real')], default='USD', max_length=3, verbose_name='Moeda Frete ALL IN (USD)'),
        ),
        migrations.AddField(
            model_name='carga',
            name='frete_rodoviario_brl',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='carga',
            name='frete_rodoviario_moeda',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dólar'), ('BRL', 'Real')], default='BRL', max_length=3, verbose_name='Moeda Frete Rodoviário'),
        ),
        migrations.AddField(
            model_name='carga',
            name='honorarios_brl',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='carga',
            name='honorarios_moeda',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dólar'), ('BRL', 'Real')], default='BRL', max_length=3, verbose_name='Moeda Honorários'),
        ),
        migrations.AddField(
            model_name='carga',
            name='licenca_importacao_brl',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='carga',
            name='licenca_importacao_moeda',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dólar'), ('BRL', 'Real')], default='BRL', max_length=3, verbose_name='Moeda Licença Importação'),
        ),
        migrations.AddField(
            model_name='carga',
            name='taxa_armazenagem_brl',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='carga',
            name='taxa_armazenagem_moeda',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dólar'), ('BRL', 'Real')], default='BRL', max_length=3, verbose_name='Moeda Taxa Armazenagem'),
        ),
        migrations.AddField(
            model_name='carga',
            name='taxa_siscomex_brl',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='carga',
            name='taxa_siscomex_moeda',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dólar'), ('BRL', 'Real')], default='BRL', max_length=3, verbose_name='Moeda Taxa Siscomex'),
        ),
        migrations.AlterField(
            model_name='carga',
            name='frete_all_in_moeda',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dólar'), ('BRL', 'Real')], default='EUR', max_length=3, verbose_name='Moeda'),
        ),
    ]
