# Generated by Django 5.1.2 on 2025-06-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0019_remove_gridinternacional_ultimo_grid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='cotacao_usada',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carga',
            name='frete_all_in_brl',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='carga',
            name='frete_all_in_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Frete ALL IN (EUR)'),
        ),
        migrations.AlterField(
            model_name='carga',
            name='frete_rodoviario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='carga',
            name='honorarios',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='carga',
            name='licenca_importacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='carga',
            name='qtd_equipamento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carga',
            name='taxa_armazenagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='carga',
            name='taxa_siscomex',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='carga',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='carga',
            name='valor_por_equip',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True),
        ),
    ]
