# Generated by Django 5.1.2 on 2025-06-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0020_alter_carga_cotacao_usada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valormensalcliente',
            name='codigo_rastreio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de Rastreio'),
        ),
    ]
