# Generated by Django 5.1.2 on 2025-02-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reativacao', '0003_reativacao_data_hora_criacao_reativacao_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reativacao',
            name='cnpj',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
