# Generated by Django 5.1.2 on 2025-04-03 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reativacao', '0004_reativacao_cnpj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reativacao',
            name='data',
        ),
        migrations.AlterField(
            model_name='idiccid',
            name='ccid_equipamentos',
            field=models.CharField(blank=True, default='', max_length=8000),
        ),
        migrations.AlterField(
            model_name='idiccid',
            name='id_equipamentos',
            field=models.CharField(blank=True, default='', max_length=8000),
        ),
        migrations.AlterField(
            model_name='idiccid',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reativacao',
            name='data_hora_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reativacao',
            name='status_reativacao',
            field=models.CharField(blank=True, choices=[('Faturado', 'Faturado'), ('Não Faturado', 'Não Faturado')], default='Não Faturado', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reativacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
