# Generated by Django 5.1.2 on 2025-06-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reativacao', '0005_remove_reativacao_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reativacao',
            name='status_reativacao',
            field=models.CharField(blank=True, choices=[('Faturado', 'Faturado'), ('Não Faturado', 'Não Faturado'), ('Sem Custo', 'Sem Custo')], default='Não Faturado', max_length=100, null=True),
        ),
    ]
