# Generated by Django 5.2.3 on 2025-09-11 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrotipoproduto',
            name='nome_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto', verbose_name='Nome do Produto'),
        ),
    ]
