# Generated by Django 5.2.3 on 2025-09-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_cadastrotipoproduto_nome_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrotipoproduto',
            name='nome_produto',
            field=models.CharField(max_length=200, verbose_name='Nome do Produto'),
        ),
    ]
